export const LightImage = {
  avt: require('./light.png'),
  appLogo: require('./Logo.png'),
  abstractShape1: require('./onboarding/abstract-shape-1.png'),
  abstractShape2: require('./onboarding/abstract-shape-2.png'),
  abstractShape3: require('./onboarding/abstract-shape-3.png'),
  abstractShape4: require('./onboarding/abstract-shape-4.png'),
  clapperboard: require('./onboarding/clapperboard.png'),
  picture: require('./onboarding/picture.png'),
  round: require('./onboarding/round.png'),
  square: require('./onboarding/square.png'),
  mozy: require('./onboarding/mozy.png'),
  heart: require('./onboarding/heart.png'),
  enso: require('./onboarding/enso.png'),
  star: require('./onboarding/star.png'),
  emptyList: require('./EmptyList.png'),
  blankAvatar: require('./blankAvatar.png'),
};

export const DarkImage = {
  avt: require('./dark.png'),
  appLogo: require('./Logo.png'),
  abstractShape1: require('./onboarding/abstract-shape-1.png'),
  abstractShape2: require('./onboarding/abstract-shape-2.png'),
  abstractShape3: require('./onboarding/abstract-shape-3.png'),
  abstractShape4: require('./onboarding/abstract-shape-4.png'),
  clapperboard: require('./onboarding/clapperboard.png'),
  picture: require('./onboarding/picture.png'),
  round: require('./onboarding/round.png'),
  square: require('./onboarding/square.png'),
  mozy: require('./onboarding/mozy.png'),
  heart: require('./onboarding/heart.png'),
  enso: require('./onboarding/enso.png'),
  star: require('./onboarding/star.png'),
  emptyList: require('./EmptyList.png'),
  blankAvatar: require('./blankAvatar.png'),
};
